In [5]:
import pandas as pd
import numpy as np

### Question 1

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [6]:
pd.__version__

'2.1.0'

### Getting the data 

For this homework, we'll use the California Housing Prices dataset. Download it from 
[here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv).

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

In [1]:
!ls

homework.ipynb	homework.md  housing.csv


In [7]:
df = pd.read_csv("housing.csv")

### Question 2

How many columns are in the dataset?

In [5]:
df.shape

(20640, 10)

### Question 3

Which columns in the dataset have missing values?

In [7]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 4

How many unique values does the `ocean_proximity` column have?

In [9]:
df.ocean_proximity.value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [12]:
df.ocean_proximity.nunique()

5

### Question 5

What's the average value of the `median_house_value` for the houses located near the bay?

In [17]:
df.query("ocean_proximity == 'NEAR BAY'").median_house_value.describe()

count      2290.000000
mean     259212.311790
std      122818.537064
min       22500.000000
25%      162500.000000
50%      233800.000000
75%      345700.000000
max      500001.000000
Name: median_house_value, dtype: float64

### Question 6

1. Calculate the average of `total_bedrooms` column in the dataset.
2. Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
3. Now, calculate the average of `total_bedrooms` again.
4. Has it changed?

Has it changed?

> Hint: take into account only 3 digits after the decimal point.

In [22]:
df.total_bedrooms.mean()

537.8705525375618

In [21]:
df.total_bedrooms.fillna(df.total_bedrooms.mean()).mean()

537.8705525375617

### Question 7

1. Select all the options located on islands.
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the value of the last element of `w`?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [2]:
"housing_median_age, total_rooms, total_bedrooms".split(", ")

['housing_median_age', 'total_rooms', 'total_bedrooms']

In [9]:
q = df.query("ocean_proximity == 'ISLAND'")[['housing_median_age', 'total_rooms', 'total_bedrooms']]
q

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [10]:
X = q.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [11]:
X.T.dot(X)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [12]:
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [13]:
IXTX = np.linalg.inv(XTX)
IXTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [14]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [15]:
w = (IXTX @ X.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])

## Submit the results

* Submit your results here: https://forms.gle/jneGM91mzDZ23i8HA
* You can submit your solution multiple times. In this case, only the last submission will be used 
* If your answer doesn't match options exactly, select the closest one

## Deadline

The deadline for submitting is 18 September 2023 (Monday), 23:00 CEST (Berlin time).

After that, the form will be closed.

